---
- name: node apt key
  apt_key:
    url:    "http://deb.nodesource.com/gpgkey/nodesource.gpg.key"
    state:  present
  register: apt_key_node
  become:   yes

- name: node repository
  apt_repository:
    repo:     deb https://deb.nodesource.com/node_7.x trusty main
    state:    present
  register: apt_repo_node
  become:   yes

- name: update ubuntu packages
  apt: update_cache=yes
  become: yes

- name: install ubuntu packages
  apt:
    name:  nodejs
    state: present
  become: yes

- name: install node modules globally
  npm:
    name:    "{{item.n}}"
    version: "{{item.v}}"
    state:   "{{item.s}}"
    global:   yes
  with_items:
    - { n: "yarn", v: "0.21.3", s: "present" }
  become: yes
